### ISSUE TITLE
the running ceremony has contribution issues.

### ISSUE THREAD

**Issue by lingering** [Unirep/ceremony#22]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vimwitch** [comment]
Thank you for the report. We found a small race condition in the backup system for the ceremony. It caused the latest reputation key to be deleted from the server. We have a fix and will be applying it soon and closing this issue.

related #21
